export const OPEN_SIDE_DRAWER = 'OPEN_SIDE_DRAWER';
export const SWITCH_NAV_MODE = 'SWITCH_NAV_MODE';
export const RESET_SIDE_DRAWER = 'RESET_SIDE_DRAWER';
export const CLOSE_MENU = 'CLOSE_MENU';
export const STOP_MENU_TRANSITION = 'STOP_MENU_TRANSITION';
export const CLOSE_SIDE_DRAWER = 'CLOSE_SIDE_DRAWER';
export const OPEN_NAVITEM_MENU = 'OPEN_NAVITEM_MENU';
export const ACTIVATE_MENU_ITEM = 'ACTIVATE_MENU_ITEM';

export const FETCH_NAVIGATION_START = 'FETCH_NAVIGATION_START';
export const FETCH_NAVIGATION_SUCCESS = 'FETCH_NAVIGATION_SUCCESS';
export const FETCH_NAVIGATION_FAILURE = 'FETCH_NAVIGATION_FAILURE';
