export const CLICK_PLAY_BUTTON = 'CLICK_PLAY_BUTTON';
export const SET_SLIDE_CONTROLS_STATUS = 'SET_SLIDE_CONTROLS_STATUS';
export const SET_ACTIVE_SLIDE = 'SET_ACTIVE_SLIDE';
export const SHOW_NEXT_SLIDE = 'SHOW_NEXT_SLIDE';
export const SHOW_PREV_SLIDE = 'SHOW_PREV_SLIDE';


export const FETCH_SLIDER_START = 'FETCH_SLIDER_START';
export const FETCH_SLIDER_SUCCESS = 'FETCH_SLIDER_SUCCESS';
export const FETCH_SLIDER_FAILURE = 'FETCH_SLIDER_FAILURE';

