
export const SET_HERO_IMAGE_INDEX = 'SET_HERO_IMAGE_INDEX';
export const SET_ACTIVE_PRODUCT_IMAGES_COLOR = 'SET_ACTIVE_PRODUCT_IMAGES_COLOR';
export const SET_PRODUCT_COUNTER = 'SET_PRODUCT_COUNTER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';


export const SET_VISIBLE_SECTION = 'SET_VISIBLE_SECTION';

export const SET_PRODUCT_RATING = 'SET_PRODUCT_RATING';
export const SET_REVIEW_FEEDBACK = 'SET_REVIEW_FEEDBACK';
export const WRITE_PRODUCT_REVIEW = 'WRITE_PRODUCT_REVIEW';
export const ASK_PRODUCT_QUESTION = 'ASK_PRODUCT_QUESTION';


export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'; 
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'; 
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'; 

